version: '2.1'
services:
  server:
    container_name: nodejs-computer-vision-server
    build: .
    command: npm start
    depends_on:
      - postgres
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
  postgres:
    container_name: nodejs-computer-vision-postgres
    image: postgres:9.6.2-alpine
    restart: always
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
     - "5432:5432"

volumes:
  postgres-data:
