version: '2.1'
services:
  server:
    container_name: nodejs-computer-vision
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
